# Generated by Django 5.1.4 on 2026-07-15 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('host', models.CharField(blank=True, default='', max_length=255)),
                ('preparation', models.CharField(blank=True, default='', max_length=255)),
                ('participants', models.TextField(blank=True, default='')),
                ('location', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meetings', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='accounts.unit')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
